#!/usr/bin/env bash

# Freeciv - Copyright (C) 2022-2024 The Freeciv Team
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2, or (at your option)
#  any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.

DATADIR="$(cd $(dirname "$0")/../data ; pwd)"
SCENDIR="$(cd $(dirname "$0")/../data/scenarios ; pwd)"

echo "#!/usr/bin/env bash"                                                        > "$1"
echo "# Generated by $(basename "$0")"                                           >> "$1"
echo                                                                             >> "$1"
echo "if test \"\$1\" = \"--help\" || test \"\$1\" = \"-h\" ||"                  >> "$1"
echo "   test \"\$1\" = \"\" ; then"                                             >> "$1"
echo "  echo \"Usage: ./run.sh <executable> [parameters] ...\""                  >> "$1"
echo "  exit"                                                                    >> "$1"
echo "fi"                                                                        >> "$1"
echo                                                                             >> "$1"
echo "if test \"\${FREECIV_DATA_PATH}\" = \"\" ; then"                           >> "$1"
echo "  FREECIV_DATA_PATH=\"${2}/${3}:${DATADIR}\""                              >> "$1"
echo "else"                                                                      >> "$1"
echo "  FREECIV_DATA_PATH=\"\${FREECIV_DATA_PATH}:${2}/${3}:${DATADIR}\""        >> "$1"
echo "fi"                                                                        >> "$1"
echo "export FREECIV_DATA_PATH"                                                  >> "$1"
echo "if test \"\$FREECIV_SCENARIO_PATH\" = \"\" ; then"                         >> "$1"
echo "  FREECIV_SCENARIO_PATH=\"${2}/${3}/scenarios:${2}/scenarios:${SCENDIR}\"" >> "$1"
echo "else"                                                                      >> "$1"
echo "  FREECIV_SCENARIO_PATH=\"\${FREECIV_SCENARIO_PATH}:${2}/${3}/scenarios:${2}/scenarios:${SCENDIR}\"" >> "$1"
echo "fi"                                                                        >> "$1"
echo "export FREECIV_SCENARIO_PATH"                                              >> "$1"
echo "if test \"\${FREECIV_SAVE_PATH}\" = \"\" ; then"                           >> "$1"
echo "  FREECIV_SAVE_PATH=\"${2}/saves:.\""                                      >> "$1"
echo "else"                                                                      >> "$1"
echo "  FREECIV_SAVE_PATH=\"\${FREECIV_SAVE_PATH}:${2}/saves:.\""                >> "$1"
echo "fi"                                                                        >> "$1"
echo "export FREECIV_SAVE_PATH"                                                  >> "$1"
echo                                                                             >> "$1"
echo "port_in_use() {"                                                           >> "$1"
echo "  local port=\"\$1\""                                                      >> "$1"
echo "  if command -v ss >/dev/null 2>&1; then"                                  >> "$1"
echo "    ss -ltn 2>/dev/null | tail -n +2 | awk '{print \$4}' | grep -q \":\${port}\$\"" >> "$1"
echo "    return \$?"                                                            >> "$1"
echo "  fi"                                                                      >> "$1"
echo "  if command -v lsof >/dev/null 2>&1; then"                                >> "$1"
echo "    lsof -iTCP:\"\${port}\" -sTCP:LISTEN -P -n >/dev/null 2>&1"            >> "$1"
echo "    return \$?"                                                            >> "$1"
echo "  fi"                                                                      >> "$1"
echo "  return 1"                                                                >> "$1"
echo "}"                                                                         >> "$1"
echo                                                                             >> "$1"
echo ": \"\${FREECIV_LUAREMOTE_PORT:=4444}\""                                    >> "$1"
echo "base_port=\"\${FREECIV_LUAREMOTE_PORT}\""                                  >> "$1"
echo "offset=0"                                                                  >> "$1"
echo "luaremote_port=\"\${base_port}\""                                          >> "$1"
echo "while port_in_use \"\${luaremote_port}\"; do"                              >> "$1"
echo "  offset=\$((offset + 1))"                                                 >> "$1"
echo "  luaremote_port=\$((base_port + offset))"                                 >> "$1"
echo "done"                                                                      >> "$1"
echo "if test \"\${luaremote_port}\" != \"\${FREECIV_LUAREMOTE_PORT}\"; then"    >> "$1"
echo "  echo \"LuaRemote port \${FREECIV_LUAREMOTE_PORT} in use; using \${luaremote_port}\" >&2" >> "$1"
echo "fi"                                                                        >> "$1"
echo "FREECIV_LUAREMOTE_PORT=\"\${luaremote_port}\""                             >> "$1"
echo "export FREECIV_LUAREMOTE_PORT"                                             >> "$1"
echo                                                                             >> "$1"
echo "./\$@"                                                                     >> "$1"

chmod +x "$1"
